# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'actualizando.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setStyleSheet("background-image: url(Fondo.png);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 306, 1200, 113))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(trasnp.png);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cartelestadoactualizar = QtWidgets.QLabel(Form)
        self.cartelestadoactualizar.setGeometry(QtCore.QRect(460, 526, 243, 59))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(20)
        self.cartelestadoactualizar.setFont(font)
        self.cartelestadoactualizar.setStyleSheet("background-image: url(trasnp.png);")
        self.cartelestadoactualizar.setAlignment(QtCore.Qt.AlignCenter)
        self.cartelestadoactualizar.setObjectName("cartelestadoactualizar")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 410, 221,57))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(20)
        self.cartelestadoactualizar.hide()
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-image: url(Seleccionar perfil fondo botones.png);\n"
                                           "border-image: url(Seleccionar perfil fondo botones.png);")

        #self.pushButtoncancelar = QtWidgets.QPushButton(Form)
        #self.pushButtoncancelar.setGeometry(QtCore.QRect(350, 410, 221, 57))
        #self.pushButtoncancelar.setFont(font)
        #self.pushButtoncancelar.setObjectName("pushButtoncancelar")
        #self.pushButtoncancelar.setStyleSheet("background-image: url(Seleccionar perfil fondo botones.png);\n"
                                         #  "border-image: url(Seleccionar perfil fondo botones.png);")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head><body><p><span style=\" font-size:20pt; font-weight:600; color:#464646;\">Actualizando.. <span><span style=\" font-size:20pt; color:#f1f1f1;\">aguarde un instante por favor. Una vez finalizado el proceso, el sistema se reiniciará.<span><p><body><html>"))
        self.cartelestadoactualizar.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "actualizar"))
        #self.pushButtoncancelar.setText(_translate("Form", "cancelar"))

